  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loadgen-configmap
    namespace: rag
  data:
    loadgen.sh: |
      #!/bin/sh 

      for i in $(seq 20); do
      curl -X 'POST' \
        'http://rag-server.rag.svc.cluster.local:8081/generate' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{
        "messages": [
          {
            "role": "user",
            "content": "What is a CVD? Explain in detail"
          }
        ],
        "use_knowledge_base": true,
        "temperature": 0.2,
        "top_p": 0.7,
        "max_tokens": 1024,
        "top_k": 4,
        "collection_name": "nvidia_blogs",
        "model": "meta/llama-3.1-8b-instruct",
        "stop": []
      }' > /dev/null

      curl -X 'POST' \
        'http://embedqa.nim.svc.cluster.local:8000/v1/embeddings' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{
        "input": "This is some text to be embedded.",
        "model": "nvidia/llama-3.2-nv-embedqa-1b-v2",
        "input_type": "query",
        "encoding_format": "float",
        "dimensions": null,
        "user": "user-identifier",
        "truncate": "NONE"
      }' > /dev/null

          sleep 5
      done