apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadgen-cronjob-parallel
  namespace: rag
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            splunk.com/exclude: "true"
        spec:
          containers:
            - name: loadgen-parallel
              image: radial/busyboxplus:curl
              imagePullPolicy: IfNotPresent
              command: [ "/script/loadgen.sh" ]
              volumeMounts:
                - name: script
                  mountPath: "/script"
          volumes:
            - name: script
              configMap:
                name: loadgen-configmap
                defaultMode: 0744
          restartPolicy: Never
      parallelism: 50
  concurrencyPolicy: Allow