imagePullSecret:
  name: "ngc-secret"

ragServer:
  concurrentWorkers: 32
  image:
    repository: ghcr.io/dmitchsplunk/rag-server
    tag: "v1.0.0-with-otel"
    #    repository: nvcr.io/nvidia/blueprint/rag-server
    # tag: "1.0.0"
    pullPolicy: IfNotPresent
  name: rag-server
  replicas: 1
  nodeSelector: {}
  tolerations: {}
  affinity: {}
  env:
    OPENBLAS_NUM_THREADS: "1"
    EXAMPLE_PATH: 'src/'
    PROMPT_CONFIG_FILE: "/prompt.yaml"
    APP_VECTORSTORE_URL: "http://milvus-deployment.milvus:19530"
    APP_VECTORSTORE_NAME: "milvus"
    APP_VECTORSTORE_INDEXTYPE: GPU_CAGRA
    COLLECTION_NAME: nvidia_blogs
    APP_LLM_SERVERURL: "llm.nim:8000"
    APP_LLM_MODELNAME: meta/llama-3.1-8b-instruct
    APP_LLM_MODELENGINE: nvidia-ai-endpoints
    APP_EMBEDDINGS_SERVERURL: "embedqa.nim:8000"
    APP_EMBEDDINGS_MODELNAME: nvidia/llama-3.2-nv-embedqa-1b-v2
    APP_EMBEDDINGS_MODELENGINE: nvidia-ai-endpoints
    APP_RANKING_MODELNAME: nvidia/llama-3.2-nv-rerankqa-1b-v2
    APP_RANKING_MODELENGINE: nvidia-ai-endpoints
    APP_RANKING_SERVERURL: "rerankqa.nim:8000"
    APP_TEXTSPLITTER_MODELNAME: nvidia/llama-3.2-nv-embedqa-1b-v1
    APP_TEXTSPLITTER_CHUNKSIZE: 2000
    APP_TEXTSPLITTER_CHUNKOVERLAP: 200
    APP_RETRIEVER_SCORETHRESHOLD: 0.25
    CONVERSATION_HISTORY: 5
    APP_RETRIEVER_TOPK: 4
    VECTOR_DB_TOPK: 20
    LOGLEVEL: INFO
    ENABLE_MULTITURN: true
    ENABLE_QUERYREWRITER: true
    OTEL_SERVICE_NAME: "rag-server"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=ai-pod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://ucs-otel-collector-splunk-otel-collector-agent.otel.svc.cluster.local:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  service:
    type: NodePort
    targetPort: 8081
    ports:
      - port: 8081
        targetPort: http
        protocol: TCP
        name: http

ragPlayground:
  image:
    repository: ghcr.io/dmitchsplunk/rag-playground
    tag: "v1.0.0-with-otel"
    #pullPolicy: Always
    #repository: nvcr.io/nvidia/blueprint/rag-playground
    #tag: "1.0.0"
    pullPolicy: IfNotPresent
  name: rag-playground
  replicas: 1
  nodeSelector: {}
  tolerations: {}
  affinity: {}
  env:
    APP_SERVERURL: "http://rag-server"
    APP_SERVERPORT: 8081
    APP_MODELNAME: meta/llama-3.1-8b-instruct
    OTEL_SERVICE_NAME: "rag-playground"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=ai-pod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://ucs-otel-collector-splunk-otel-collector-agent.otel.svc.cluster.local:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  service:
    type: NodePort
    targetPort: 8090
    ports:
      - port: 8090
        targetPort: http
        protocol: TCP
        name: http